HW_10/HW_web_10/HW_web_10/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quotes.urls')),
    path('users/', include('users.urls')),

]

HW_10/HW_web_10/quotes/urls.py
from django.urls import path
from .views import add_author, add_quote, main, author_detail, find_by_tag

app_name = 'quotes'

urlpatterns = [
    path('', main, name='main'),
    path('add_author/', add_author, name='add_author'),
    path('add_quote/', add_quote, name='add_quote'),
    path('author_detail/<int:id>/', author_detail, name='author_detail'),
    path('tag/<int:_id>/', find_by_tag, name='find_by_tag'),

]

HW_10/HW_web_10/users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView

from .forms import LoginForm
from .views import RegisterView, ResetPasswordView

app_name = 'users'

urlpatterns = [
    path('signup/', RegisterView.as_view(), name='register'),
    path('signin/', LoginView.as_view(template_name='users/signin.html',
                                      authentication_form=LoginForm,
                                      redirect_authenticated_user=True
                                      ), name='login'),
    path('logout/', LogoutView.as_view(template_name='users/logout.html',
                                       ), name='logout'),
    path('reset-password/', ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

HW_10/HW_web_10/quotes/models.py
from django.db import models


class Author(models.Model):
    fullname = models.CharField(max_length=255)
    born_date = models.CharField(max_length=255)
    born_location = models.CharField(max_length=255)
    description = models.TextField()

    def __str__(self):
        return self.fullname


class Quote(models.Model):
    text = models.TextField()
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    tags = models.ManyToManyField('Tag')

    def __str__(self):
        return self.text


class Tag(models.Model):
    tag = models.CharField(max_length=255)

    def __str__(self):
        return self.tag

HW_10/HW_web_10/users/models.py
from django.db import models

# Create your models here.

HW_10/HW_web_10/quotes/forms.py
from django import forms
from .models import Author, Quote


class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ['fullname', 'born_date', 'born_location', 'description']


class QuoteForm(forms.ModelForm):
    class Meta:
        model = Quote
        fields = ['tags', 'text', 'author']

HW_10/HW_web_10/users/forms.py
from django.forms import ModelForm, CharField, TextInput, EmailField, EmailInput, PasswordInput
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm


class RegisterForm(UserCreationForm):
    username = CharField(max_length=100, required=True, widget=TextInput(attrs={'class': 'form-control'}))
    email = EmailField(max_length=100, required=True, widget=TextInput(attrs={'class': 'form-control'}))
    password1 = CharField(max_length=12, min_length=4, required=True,
                          widget=PasswordInput(attrs={'class': 'form-control'}))
    password2 = CharField(max_length=12, min_length=4, required=True,
                          widget=PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class LoginForm(AuthenticationForm):
    username = CharField(max_length=100, required=True, widget=TextInput(attrs={'class': 'form-control'}))
    password = CharField(max_length=12, min_length=4, required=True,
                         widget=PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ('username', 'password')

HW_10/HW_web_10/quotes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.contrib.auth.decorators import login_required
from .forms import AuthorForm, QuoteForm
from .models import Author, Quote, Tag


def main(request):
    quotes = Quote.objects.all()
    authors = Author.objects.all()
    tags = Tag.objects.all()
    context = {
        'quotes': quotes,
        'authors': authors,
        'tags': tags
    }
    return render(request, 'quotes/base.html', context)


def author_detail(request, id):
    author = Author.objects.get(pk=id)
    context = {
        'author': author
    }

    return render(request, 'quotes/author_detail.html', context)


def find_by_tag(request, _id):
    per_page = 5
    if isinstance(_id, int):
        quotes = Quote.objects.filter(tags=_id).all()
    elif isinstance(_id, str):
        _id = Tag.objects.filter(name=_id).first()
        quotes = Quote.objects.filter(tags=_id.id).all()
    context = {'quotes': quotes}
    return render(request, 'quotes/base.html', context)


"""class AuthorCreateView(View):
    form_class = AuthorForm
    template_name = 'quotes/author_add.html'

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            author = form.save()
            return redirect('author_detail', pk=author.pk)
        return render(request, self.template_name, {'form': form})"""


@login_required
def add_author(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request, 'quotes/base.html', )
    else:
        form = AuthorForm()
    return render(request, 'quotes/author_add.html', {'form': form})


@login_required
def add_quote(request):
    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request, 'quotes/base.html')

    else:
        form = QuoteForm()
    return render(request, 'quotes/add_quote.html', {'form': form})

HW_10/HW_web_10/users/views.py
from django import dispatch
from django.shortcuts import render, redirect
from django.views import View
from .forms import RegisterForm
from django.contrib import messages
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy


# Create your views here.
class RegisterView(View):
    form_class = RegisterForm
    template_name = 'users/signup.html'

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect(to="app_instagram:home")
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        return render(request, self.template_name, {'form': self.form_class})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            messages.success(request, f'Вітаємо {username}')
            return redirect(to='users:login')
        return render(request, self.template_name, {'form': form})


class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'users/password_reset.html'
    email_template_name = 'users/password_reset_email.html'
    html_email_template_name = 'users/password_reset_email.html'
    success_url = reverse_lazy('users:password_reset_done')
    success_message = "An email with instructions to reset your password has been sent to %(email)s."
    subject_template_name = 'users/password_reset_subject.txt'

HW_10/HW_web_10/quotes/templates/quotes/add_quote.html
{% extends 'quotes/base.html' %}
{% block main %}
<h2>Add Quote</h2>
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Add</button>
</form>
{% endblock %}

HW_10/HW_web_10/quotes/templates/quotes/author_add.html
{% extends 'quotes/base.html' %}
{% block main %}
<h2>Add Author</h2>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Add</button>
</form>
{% endblock %}

HW_10/HW_web_10/quotes/templates/quotes/author_detail.html
{% extends 'quotes/base.html' %}

{% block main %}
<div class="author-detail">
    <h2>{{ author.fullname }}</h2>
    <p>Born: {{ author.born_date }} in {{ author.born_location }}</p>
    <p>Description: {{ author.description }}</p>
    <h3>Quotes:</h3>
    <ul>
        {% for quote in author.quotes.all %}
        <li>{{ quote.text }}</li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

HW_10/HW_web_10/quotes/templates/quotes/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'app_instagram/style.css' %}">
    <title>{{ title }}</title>
</head>
<body>
<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
    <header class="mb-auto">
        <div>
            <h3 class="float-md-start mb-0">Cover</h3>
            <nav class="nav nav-masthead justify-content-center float-md-end">

                {% if user.is_authenticated %}
                <a class="nav-link fw-bold active" aria-current="page" href="{% url 'quotes:main' %}">Quotes</a>
                <a class="nav-link fw-bold" href="{% url 'quotes:add_author' %}">Add author</a>
                <a class="nav-link fw-bold" href="{% url 'quotes:add_quote' %}">Add quote</a>
                <a class="nav-link fw-bold " href="{% url 'users:logout' %}"> Logout </a>
                {% else %}
                <a class="nav-link fw-bold " href="{% url 'users:register' %}">SignUp</a>
                <a class="nav-link fw-bold " href="{% url 'users:login' %}"> SignIn</a>
                {% endif %}
            </nav>
        </div>
    </header>
    {% block main %}
    {% for quote in quotes %}
    <div class="quote" itemscope itemtype="http://schema.org/CreativeWork">
        <span class="text" itemprop="text">{{ quote.text }}</span>
        <span>by <small class="author" itemprop="author">{{ quote.author }}</small>
    <a href="{% url 'quotes:author_detail' quote.author.id %}">(about)</a>
    </span>
        <div class="tags">
            Tags:
            {% for tag in quote.tags.all %}
            <a class="tag" href="{% url 'quotes:find_by_tag' tag.id %}">{{tag}}</a>
            {% endfor %}
        </div>
    </div>
    {% endfor %}
    {% endblock %}

    <footer class="mt-auto text-white-50">
        <p>Web Python 10 <a href="https://getbootstrap.com/" class="text-white">Bootstrap</a>, by <a
                href="https://twitter.com/mdo" class="text-white">@mdo</a>.</p>
    </footer>
</div>
</body>
</html>

HW_10/HW_web_10/users/templates/users/logout.html
{% extends "quotes/base.html" %}

{% block main %}


<h1> Повернись назад! НЕ йди</h1>


{% endblock %}

HW_10/HW_web_10/users/templates/users/password_reset.html
{% extends "quotes/base.html" %}

{% block main %}

<h2>Password reset</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Request password reset</button>
</form>

{% endblock %}

HW_10/HW_web_10/users/templates/users/password_reset_complete.html
{% extends "quotes/base.html" %}

{% block main %}

<h2>Password reset complete!</h2>

{% endblock %}

HW_10/HW_web_10/users/templates/users/password_reset_confirm.html
{% extends "quotes/base.html" %}

{% block main %}

<h2>Enter new password</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save new password</button>
</form>

{% endblock %}

HW_10/HW_web_10/users/templates/users/password_reset_done.html
{% extends "quotes/base.html" %}

{% block main %}

<h2>Password reset request sent</h2>
<p>We've emailed you with instructions on how to reset your password.</p>

{% endblock %}

HW_10/HW_web_10/users/templates/users/password_reset_email.html
{% autoescape off %}
<body>
<p>Hi {{ user.username }},</p>
<p>You requested a password reset for your account. Please follow this link to set a new password:</p>
<p>
    <a href="{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}">
        {{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
    </a>
</p>
<p>If you didn't request a password reset, please ignore this email.</p>
<p>Thanks,</p>
<p>The Our Team</p>
{% endautoescape %}

HW_10/HW_web_10/users/templates/users/signin.html
{% extends "quotes/base.html" %}

{% block main %}
<h3>SignIn</h3>

{% if form.errors %}
<span class="alert alert-danger" role="alert">{{ form.non_field_errors }}</span>
{% endif %}

{% if messages %}
{% for message in messages %}
<span class="alert {% if message.tags %} alert-{{message.tags}} {% endif %}" role="alert">{{message}} </span>
{% endfor %}
{% endif %}

<form method="post">
    {% csrf_token %}
    <div class='row mb-3'>
        <label for="{{ form.username.id_for_label }}">Username</label>
        {{ form.username }}
        {% if form.errors %}
        <span class="alert alert-danger" role="alert">{{ form.errors.description }}</span>
        {% endif %}
    </div>
    <div class='row mb-3'>
        <label for="{{ form.password.id_for_label }}">Password</label>
        {{ form.password }}
        {% if form.errors %}
        <span class="alert alert-danger" role="alert">{{ form.errors.description }}</span>
        {% endif %}
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
    <button type="reset" class="btn btn-info">Reset</button>
    <div class="small text-center">
        <a href="{% url 'users:password_reset' %}" class="text-center"><i>Forgot Password?</i></a>
    </div>
</form>


{% endblock %}

HW_10/HW_web_10/users/templates/users/signup.html
{% extends "quotes/base.html" %}

{% block main %}
<h3>SignUp</h3>
{% if form.errors %}
<span class="alert alert-danger" role="alert">{{ form.non_field_errors }}</span>
{% endif %}
<form method="post">
    {% csrf_token %}
    <div class='row mb-3'>
        <label>Username</label>
        {{ form.username }}
        {% if form.errors %}
        <span class="alert alert-danger" role="alert">{{ form.errors.description }}</span>
        {% endif %}
    </div>
    <div class='row mb-3'>
        <label>Email</label>
        {{ form.email }}
        {% if form.errors %}
        <span class="alert alert-danger" role="alert">{{ form.errors.description }}</span>
        {% endif %}
    </div>
    <div class='row mb-3'>
        <label>Password1</label>
        {{ form.password1 }}
        {% if form.errors %}
        <span class="alert alert-danger" role="alert">{{ form.errors.description }}</span>
        {% endif %}
    </div>
    <div class='row mb-3'>
        <label>Repeat password</label>
        {{ form.password2 }}
        {% if form.errors %}
        <span class="alert alert-danger" role="alert">{{ form.errors.description }}</span>
        {% endif %}
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
    <button type="reset" class="btn btn-info">Reset</button>
</form>


{% endblock %}